### PR TITLE
update to core beta 1

### PR DESCRIPTION
**Pull request by SimonCropp**
Connects to https://github.com/Particular/PlatformDevelopment/issues/718

### CODE REVIEW

**Comment by SeanFeldman** [comment]
The build is failing @SimonCropp 
@boblangley should we take out Endurance test out of the transport solution?

**Comment by boblangley** [comment]
Yes since it will be moved/adapted to EndToEnd.

**Comment by SeanFeldman** [comment]
:+1: I'll take if off the solution (to avoid compilation nuances), but keep in the repo for now.

**Comment by SeanFeldman** [comment]
@SimonCropp done

**Pull request merged**
