### PR TITLE
fixed bug with individualized subscription name lengths >= 50

### PR DESCRIPTION
**Pull request by johningle**
Added logic to detect individualized subscription name lengths >= 50 and
utilize deterministic guids.  Name lengths < 50 go through the prior
convention logic.

### CODE REVIEW

**Comment by SeanFeldman** [comment]
@johningle - thank you for PR.
I have gone through suggested change and think we'll need to come up with a different strategy here. Change has to be backwards compatible to ensure other users are not broken by the change. Consider the following scenario:

Event: `Some.Namespace.Events.EventNameThatExceedsMaximumLength` (55 chars, exceeds max 50)
Machine name: `JOHNI-D`

Today, this will be converted into a deterministic GUID (`8e8faf92-24b0-6296-e76b-f34231bdb758`) and individualized resulting in subscription name `8e8faf92-24b0-6296-e76b-f34231bdb758-JOHNI-D`

If PR is applied, same subscription will result in subscription name `39f0981d-c539-2c08-ea74-141cab944843`.

**Comment by johningle** [comment]
@SeanFeldman - Thank you for the review Sean, I see the issue and have come up with the following scenarios that any fix will need to account for:

1. subscription name length < 50 characters, no guid calculated, should not individualize, so final name length < 50 characters, backward compatible, handled by existing code
2. subscription name length < 50 characters, no guid calculated, should not individualize, so final name length >= 50 characters is impossible since original name length < 50 and not changed, backward compatible, handled by existing code
3. subscription name length < 50 characters, no guid calculated, should individualize, and final name length < 50 characters, backward compatible, handled by existing code
4. subscription name length >= 50 characters, guid calculated, should not individualize, and final name length < 50 characters, backward compatible, handled by existing code
5. subscription name length >= 50 characters, guid calculated, should not individualize, and final name length >= 50 characters is impossible since guid length < 50, backward compatible, handled by existing code
6. subscription name length >= 50 characters, guid calculated, should individualize, and final name length < 50 characters, backward compatible, handled by existing code

7. subscription name length < 50 characters, no guid calculated, should individualize, and final name length >= 50 characters, individualization sent it over, not handled by existing code, no need for backward compatible solution because it causes an exception, need fix
8. subscription name length >= 50 characters, guid calculated, should individualize, and final name length >= 50 characters, individualization sent it over, not handled by existing code, no need for backward compatible solution because it causes an exception, need fix

I have since committed a revision that I believe accounts for all of these scenarios while retaining backward compatibility.
No existing environment should contain object names meeting cases 7 and 8 because the excessive length would cause an exception in Microsoft's Service Bus DLL and prevent creation of the object.

**Comment by SeanFeldman** [comment]
@johningle :+1: for backwards compatibility.
@yvesgoeleven what do you think?

**Comment by yvesgoeleven** [comment]
Thank you for this PR! @johningle

**Comment by SeanFeldman** [comment]
related issue: #40

**Comment by malkinservicebus** [comment]
Hi @johningle - Thank You for PR.
We have a surprise for your. Please forward  your email address to operations@nservicebus.com
Thanks again!
Malki

**Comment by johningle** [comment]
@malkinservicebus I'm afraid that I am only just seeing your response.  Though it has been a few months, can I still get the surprise?

**Comment by malkinservicebus** [comment]
sure @johningle on condition that you send me your address :)

**Comment by johningle** [comment]
@malkinservicebus Sent!

**Comment by malkinservicebus** [comment]
:+1:

**Pull request merged**
