### PR TITLE
[WIP] Update core

### PR DESCRIPTION
**Pull request by timbussmann**
- [x] Raise a core issue for the acceptance test fixes @danielmarbach (https://github.com/Particular/NServiceBus/pull/4432)

### CODE REVIEW

**Comment by SeanFeldman** [comment]
@timbussmann what about [this PR](https://github.com/Particular/NServiceBus.AzureServiceBus/pull/418)? Perhaps merge the two?

**Comment by timbussmann** [comment]
@SeanFeldman I think we can close #418 as I think this was used as a spike to verify the approach with the metadata works for ASB. This PR should contain the same changes. Thoughts @andreasohlund ?

**Comment by timbussmann** [comment]
@Particular/azure-maintainers can you have a look at the failing tests, e.g. `When_sending_events_bestpractices_disabled`. I don't know why it complains about missing registered publishers when it actually calls `Send<Event>()`.

**Comment by SeanFeldman** [comment]
@timbussmann I just tried the branch locally and `When_sending_events_bestpractices_disabled` works. Is this something that is failing for you locally? What data centre are you connecting to?

**Comment by SeanFeldman** [comment]
Now looking at it, those tests should not be executed at all. They are all marked as run for `AllTransportsWithMessageDrivenPubSub`, and ASB doesn't support that.

**Comment by timbussmann** [comment]
@SeanFeldman I run the tests locally, and the same tests failing here: https://builds.particular.net/viewLog.html?buildId=201568&tab=buildResultsDiv&buildTypeId=NServiceBusAzure_NServiceBusAzureServiceBus_2RunAcceptenceTests also fail on my machine.

I think I could use some help to look into this.

**Comment by danielmarbach** [comment]
- Fixed the tests which check for MessageTooLargeException
- Registered metadata for endpoint-oriented topology where still required
- Dynamically ignored unsupported tests

**Comment by timbussmann** [comment]
@Particular/azure-maintainers 6.1 is now officially released. Feel free to pick up this PR and update it to the final 6.1 package. It's up to you whether you decide to only update the test projects or if you update the main projects build dependency to 6.1 too. In case of the second option, please be careful to update nuspec dependencies only if you make use of newly available 6.1 APIs.

**Comment by SeanFeldman** [comment]
Tests are passing locally (confirmed `ForwardingTopology`, @boblangley to confirm `EndpointOrientedTopology`).

**Comment by boblangley** [comment]
`EndpointOrientedTopology` tests all passed locally.

**Comment by SeanFeldman** [comment]
Investigation led to a discovery of a bug in ATTs FW (https://github.com/Particular/NServiceBus.AzureServiceBus/pull/479#issuecomment-274208995). To continue with this PR, a new version of ATTs FW is needed.

**Comment by SeanFeldman** [comment]
Update: pending Core PR https://github.com/Particular/NServiceBus/pull/4437

**Comment by danielmarbach** [comment]
@Particular/azure-maintainers updated to NServiceBus.AcceptanceTesting 6.2.0-alpha0166 let's see how it goes

**Comment by SeanFeldman** [comment]
I've had a mixed experience. Builds are failing on random tests that work locally and wouldn't be expected to fail. Number of those failures very from [1 to 33](https://builds.particular.net/viewType.html?buildTypeId=NServiceBusAzure_NServiceBusAzureServiceBus_2RunAcceptenceTests&branch_NServiceBusAzure_NServiceBusAzureServiceBus=449&tab=buildTypeStatusDiv). I'm not comfortable with merging this until it's a solid green for some time.

**Comment by timbussmann** [comment]
closing this as there doesn't seem to be activity around this.

**Pull request closed without merging**
