### PR TITLE
nuget version shield

### PR DESCRIPTION
**Pull request by SeanFeldman**
@Particular/azure-host-maintainers this will show what's the current version of the transport we have on nuget straight on the readme.md

### CODE REVIEW

**Comment by boblangley** [comment]
Was this meant for @Particular/azure-service-bus-maintainers ?

Either way, I like the change.

**Comment by SeanFeldman** [comment]
haha, yes @boblangley 
@Particular/azure-service-bus-maintainers any objections?

**Comment by boblangley** [comment]
Merged #382

**Comment by SeanFeldman** [comment]
Congrats on your first merge as a maintainer @boblangley! :)

**Pull request merged**
