### PR TITLE
Get rid off SettingsHolderFactory because it is not needed

### PR DESCRIPTION
**Pull request by danielmarbach**

### CODE REVIEW

**Comment by SeanFeldman** [comment]
Failing tests require serializer to be set.

**Comment by danielmarbach** [comment]
Yes saw that. Will introduce an extension method thaz does it and then use it where needed

**Comment by SeanFeldman** [comment]
For soon to be deprecated legacy transport this kind of refactoring doesn't add anything. Not sure it's worthy but will defer to you.

**Comment by danielmarbach** [comment]
To be frank I did change this because SC had a few hacks in the code that where no longer necessary and figured I can make the situation a bit better. Anyway

**Pull request closed without merging**
