### PR TITLE
ASB 3.4.3 update

### PR DESCRIPTION
**Pull request by SeanFeldman**
Update to the latest MSFT ASB

### CODE REVIEW

**Comment by SeanFeldman** [comment]
@Particular/azure-maintainers at your leasure

**Comment by tmasternak** [comment]
adding `WIP` unitil we make the build green

**Comment by SeanFeldman** [comment]
@tmasternak don't think we need a `WIP` as there's absolutely nothing to work on 😄 
Build should be green shortly so should be good to go.

**Comment by danielmarbach** [comment]
@SeanFeldman WIP is a convention most repos use to indicate it cannot be merged. There is even a chrome plugin which greys out the merge buttons

**Comment by SeanFeldman** [comment]
@danielmarbach careful, that plugin not always works. I always saw WIP as a convention to communicate "should not be merged", not "cannot be merged". I.e. the authors of PR indicate that it's still in progress and should not be attempted to be merged. Semantics 😄 

Removing WIP, @Particular/azure-maintainers good to go.

**Comment by boblangley** [comment]
merged #442

**Pull request merged**
