### PR TITLE
Adjust namespaces

### PR DESCRIPTION
**Pull request by melkio**
Connects to #263 

Rules described [here](https://github.com/Particular/PlatformDevelopment/blob/master/designprinciples/nservicebus/component-naming.md) and [here](https://github.com/Particular/PlatformDevelopment/blob/master/designprinciples/nservicebus/namespaces.md)

@Particular/azure-service-bus-maintainers please review

### CODE REVIEW

**Comment by yvesgoeleven** [comment]
:+1: for me, after the other 2 PR's are in we should rebase this and merge

**Comment by SeanFeldman** [comment]
Rebase is needed.

@yvesgoeleven not sure which other two PRs you refereed to are. Should this be pulled in after rebase?

**Comment by yvesgoeleven** [comment]
@SeanFeldman well we said to postpone this one until they were all done (but we keep getting new)

**Comment by SeanFeldman** [comment]
Let's bring it in or is it late again?

**Comment by yvesgoeleven** [comment]
@SeanFeldman it will cause massive issues for any open PR that needs to be merged in (not sure if that is the case with the 2 open ones currently)

**Comment by SeanFeldman** [comment]
Ok, then we need to park it and act when no major PR ate pending.

**Comment by SeanFeldman** [comment]
Rebased and all green.
@Particular/azure-service-bus-maintainers please review and merge.

**Pull request merged**
