### PR TITLE
Core beta 7

### PR DESCRIPTION
**Pull request by yvesgoeleven**

### CODE REVIEW

**Comment by yvesgoeleven** [comment]
@SeanFeldman @melkio there are failing tests after the upgrade to core beta 7, can you continue this work next week and get it to myget please

**Comment by SeanFeldman** [comment]
@yvesgoeleven what was the theme for core beta 7?

**Comment by andreasohlund** [comment]
>what was the theme for core beta 7?

We had to put out a new beta of the core so it was mostly routing changes

**Comment by andreasohlund** [comment]
@SeanFeldman got all but one test green

**Comment by andreasohlund** [comment]
Think I've found the issue (tests is wrong), ping me when U get online @SeanFeldman

**Comment by SeanFeldman** [comment]
The build is green. Merging.

**Pull request merged**
