### PR TITLE
Made ToTransportAddress explicit

### PR DESCRIPTION
**Pull request by SzymonPobiega**
Replaces #316

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
@Particular/azure-service-bus-maintainers please review. The reason for making it explicit is that `ToString` includes instance properties in a semicolon separated string.

**Comment by SeanFeldman** [comment]
@SzymonPobiega is this needed for the NSB.ASB work properly with Core RC1?
I pushed RC1 to myget & updated samples w/o realising that this PR was still pending :disappointed:

**Comment by SeanFeldman** [comment]
ie can we slate it for RC2 @SzymonPobiega ?

**Comment by SzymonPobiega** [comment]
Sure

**Comment by SeanFeldman** [comment]
merged

**Pull request merged**
