### PR TITLE
Support for custom subscription filter

### PR DESCRIPTION
**Pull request by tchelidze**
- Replaced direct instantiations of SqlSubscriptionFilter and CatchAllSubscriptionFilter with indirect one via ICreateBrokerSideSubscriptionFilter factory.
- Added DefaultCreateBrokerSideSubscriptionFilter implementing an existing way of generating filter.
- Added unit test.

### CODE REVIEW

**Comment by SeanFeldman** [comment]
Related to https://github.com/Particular/NServiceBus.AzureServiceBus/issues/829

**Comment by DavidBoike** [comment]
@tchelidze 	Thanks for the PR. We'll review it and get back to you.

Although, this is for the legacy Azure Service Bus transport, as opposed to the [new transport](https://docs.particular.net/transports/azure-service-bus/). I'm not sure if we'll be adding additional features. Have you considered migrating?

**Comment by tchelidze** [comment]
> @tchelidze Thanks for the PR. We'll review it and get back to you.
> 
> Although, this is for the legacy Azure Service Bus transport, as opposed to the [new transport](https://docs.particular.net/transports/azure-service-bus/). I'm not sure if we'll be adding additional features. Have you considered migrating?

@DavidBoike Sounds good, looking forward to hearing the feedback.

Atm, we aren't planning to upgrade to the new Asb transport.

**Comment by DavidBoike** [comment]
Hi @tchelidze,

We've decided not to accept this PR, as we don't want to create any new features in the legacy Azure Service Bus transport, only fix bugs, especially when there are so many possible workarounds as have been discussed in https://github.com/Particular/NServiceBus.AzureServiceBus/issues/829 (and to which I will add another in just a second).

**Pull request closed without merging**
