### PR TITLE
Namespace Partitioning Strategy can indicate whether caching of runtime namespaces is feasible

### LINKED ISSUE #672: ASB v8 Round Robin partitioning doesn't work
## Who's affected

Anyone using Azure Service Bus transport with `RoundRobinNamespacePartitioning` strategy or custom strategy that is expected to return a different namepspace at run-time for sends and publishes.

## Symptoms 

Instead of returning a different namespace as expected, `RoundRobinNamespacePartitioning` strategy returns a cached namespace. For custom topologies, this would manifest in a similar behaviour if returned namespaces are calculated at run-time.

## Affected transport versions

- Version 7 (issue #673 )
- Version 8 (this issue)

## Original issue

As reported on https://discuss.particular.net/t/roundrobin-asb-strategy-behavior/193/3

Eventhough the RoundRobinNamespacePartitioning is set, all messages still get sent to the first namespace in the set.

I haven't had time yet to reproduce this, but I likely cause seems to be caching in the topology section manager.

https://github.com/Particular/NServiceBus.AzureServiceBus/blob/develop/src/Transport/Topology/Topologies/ForwardingTopologySectionManager.cs#L132

Once a destination is chosen, the cache will serve it over and over again, therefore nullifying the purpose of the partitioning strategy

### LINKED ISSUE #678: Publish logic relies on partitioning strategy order
Related to #674

The router filters send destinations based on the associated namespace being active

https://github.com/Particular/NServiceBus.AzureServiceBus/blob/develop/src/Transport/Sending/OutgoingBatchRouter.cs#L45

But the section manager assigns it to the first topic returned by the partitioning strategy.

https://github.com/Particular/NServiceBus.AzureServiceBus/blob/develop/src/Transport/Topology/Topologies/ForwardingTopologySectionManager.cs#L126

If that one is passive, no send will actually happen

### LINKED ISSUE #679: Incorrect filter applied for publish destinations
Related to #674

The sectionmanager selects all active topics in all active namespaces to publish to

https://github.com/Particular/NServiceBus.AzureServiceBus/blob/develop/src/Transport/Topology/Topologies/ForwardingTopologySectionManager.cs#L122

But this will result in duplicate messages if there are multiple topics in the namespace

Instead it should select a single topic from the active namespaces + all topics from the passive ones. (for fallback as the send logic applies these one by one until the send is succesfull)

### PR DESCRIPTION
**Pull request by SeanFeldman**
Fixes #672
Fixes #678
Fixes #679

This PR introduces the possibility to indicate on a namespace partitioning strategy whether the result of `GetNamespaces` can be cached for sending. The flag was named `SendingCachaeble` in order to clearly show that currently only call for `PartitioningIntent.Sending` are cached by the infrastructure. 

Verification tests to demonstrate caching issue with RoundRobin strategy in v8 #672.

### CODE REVIEW

**Comment by SeanFeldman** [comment]
Need to carefully review this and discuss during our sync.

**Comment by danielmarbach** [comment]
I wrote a bunch of ATTs that hopefully get us covered. There is one missing that we might need to add, it is about having multiple bundles

**Comment by SeanFeldman** [comment]
> There is one missing that we might need to add, it is about having multiple bundles.

What do you mean multiple bundles? Perhaps "multiple topics in a bundle"? In that case it's only for backward compatibility we no longer allow to create a bundle with multiple topics.

**Comment by danielmarbach** [comment]
Pretty sure the test failing on Forward Topology is related to #675

**Comment by danielmarbach** [comment]
Rebased. The tests should not properly run on cleaned namespaces, dirty namespaces as well as on both topologies. Please review

**Comment by danielmarbach** [comment]
@Particular/azure-maintainers can someone start smoke testing this?

**Comment by SeanFeldman** [comment]
@danielmarbach doing it today

**Comment by SeanFeldman** [comment]
Verified using [custom strategy](https://gist.github.com/janpieterz/cb24b1840ba9639b31c49b1f6303172a) provided by @janpieterz modified for ASB v8 and can confirm the transport is working as expected now. Need to fix the tests I broke 🙂

Round Robin:
image

Round Robin with fail-over:
image

<details>

<summary>RoundRobin with fail-over for ASB v8 strategy</summary>

```
public class RoundRobinPartitioningFailoverStrategy : INamespacePartitioningStrategy
{
    private readonly CircularBuffer<RuntimeNamespaceInfo[]> _namespaces;
    public RoundRobinPartitioningFailoverStrategy(ReadOnlySettings settings)
    {
        if (!settings.TryGet("AzureServiceBus.Settings.Topology.Addressing.Namespaces",
            out NamespaceConfigurations namespaces))
        {
            throw new ConfigurationErrorsException($"The '{nameof(RoundRobinPartitioningFailoverStrategy)}' strategy requires exactly two namespaces to be configured, please use {nameof(AzureServiceBusTransportExtensions.NamespacePartitioning)}().{nameof(AzureServiceBusNamespacePartitioningSettings.AddNamespace)}() to register the namespaces.");
        }
        var partitioningNamespaces = namespaces.Where(x => x.Purpose == NamespacePurpose.Partitioning).ToList();
        if (partitioningNamespaces.Count != 2)
        {
            throw new ConfigurationErrorsException($"The '{nameof(RoundRobinPartitioningFailoverStrategy)}' strategy requires exactly two namespaces to be configured, please use {nameof(AzureServiceBusTransportExtensions.NamespacePartitioning)}().{nameof(AzureServiceBusNamespacePartitioningSettings.AddNamespace)}() to register the namespaces.");
        }
        _namespaces = new CircularBuffer<RuntimeNamespaceInfo[]>(partitioningNamespaces.Count);
        var first = namespaces.First();
        var second = namespaces.Last();

        _namespaces.Put(new[]
        {
                new RuntimeNamespaceInfo(first.Alias, first.Connection, first.Purpose, NamespaceMode.Active),
                new RuntimeNamespaceInfo(second.Alias, second.Connection, second.Purpose, NamespaceMode.Passive),
            });
        _namespaces.Put(new[]
        {
                new RuntimeNamespaceInfo(first.Alias, first.Connection, first.Purpose, NamespaceMode.Passive),
                new RuntimeNamespaceInfo(second.Alias, second.Connection, second.Purpose, NamespaceMode.Active),
            });
    }
    public IEnumerable<RuntimeNamespaceInfo> GetNamespaces(PartitioningIntent partitioningIntent)
    {
        return _namespaces.Get();
    }

    public bool SendingNamespacesCanBeCached { get; } = false;
}
```

</details>

**Pull request merged**
