### PR TITLE
[WIP] release-8.0

### PR DESCRIPTION
**Pull request by yvesgoeleven**

### CODE REVIEW

**Comment by yvesgoeleven** [comment]
The generated nuspec is targetting specific version for core, not the range as specified in csproj still need to figure out why

**Comment by SeanFeldman** [comment]
You might want to mark it as WIP or BLOCKED till the issue is resolved.

**Comment by SeanFeldman** [comment]
3 tests are failing, but doubt they are related.

**Comment by SeanFeldman** [comment]
Note that merge will need to be done [manually](https://github.com/Particular/PlatformDevelopment/blob/master/guidelines/releasing/gitflow.md#merge-release-into-master-advanced).

**Comment by danielmarbach** [comment]
Switching back to develop mode

**Pull request closed without merging**
