### PR TITLE
Sanitize "composed" entityPath

### PR DESCRIPTION
**Pull request by melkio**
Connects to #156 

Sanitization strategies didn't work with composed entity path like `queueName@connectionString` or `queueName@namespaceName`.
New implementation splits `queueName` and `suffix`, then it sanitizes only `queueName`

@Particular/azure-maintainers ready to review

### CODE REVIEW

**Comment by SeanFeldman** [comment]
@melkio since we don't have a way to validate if this fix is working the way it's expected w/o touching transport compatibility tests, do you want to try locally to verify that it does work?

**Comment by melkio** [comment]
@SeanFeldman before creating the PR I tried. It works

**Comment by SeanFeldman** [comment]
@yvesgoeleven I'm :+1: with the change. Merge?

**Comment by yvesgoeleven** [comment]
Merged!

**Pull request merged**
