### PR TITLE
[SPIKE] Null reference repro

### PR DESCRIPTION
**Pull request by danielmarbach**
Trying to see if with these changes we still see the null reference exception

### CODE REVIEW

**Comment by danielmarbach** [comment]
@bording @SeanFeldman see

**Comment by bording** [comment]
Looks like it failed with -100 even with these changes.

**Comment by SeanFeldman** [comment]
Which means it is not the dispose issue as NRE happens in `NServiceBus.AcceptanceTesting.ContextAppender.Log()` 😞
Here's the event log entry from the build agent

<details><summary>Exception details</summary>
Application: nunit-agent.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.NullReferenceException: Object reference not set to an instance of an object.
   at NServiceBus.AcceptanceTesting.ContextAppender.Log(String message, LogLevel messageSeverity) in C:\Build\src\NServiceBus.AcceptanceTesting\ContextAppender.cs:line 115
   at NServiceBus.AcceptanceTesting.ContextAppender.Info(String message, Exception exception) in C:\Build\src\NServiceBus.AcceptanceTesting\ContextAppender.cs:line 50
   at NServiceBus.Transport.AzureServiceBus.MessageReceiverNotifier.OptionsOnExceptionReceived(Object sender, ExceptionReceivedEventArgs exceptionReceivedEventArgs) in C:\BuildAgent\work\2f57832e2eee436e\src\Transport\Receiving\MessageReceiverNotifier.cs:line 159
   at Microsoft.ServiceBus.Messaging.OnMessageOptions.RaiseExceptionReceived(ExceptionReceivedEventArgs e)
   at Microsoft.ServiceBus.Messaging.MessageReceivePump.RaiseExceptionReceivedEvent(Exception exception, String action)
Stack:
   at System.Environment.FailFast(System.String)
   at Microsoft.ServiceBus.Messaging.MessageReceivePump.RaiseExceptionReceivedEvent(System.Exception, System.String)
   at Microsoft.ServiceBus.Messaging.MessageReceivePump+PumpAsyncResult+<GetAsyncSteps>d__7.MoveNext()
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].EnumerateSteps(CurrentThreadType<System.__Canon>)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].StepCallback(System.IAsyncResult)
   at Microsoft.ServiceBus.Common.AsyncResult.AsyncCompletionWrapperCallback(System.IAsyncResult)
   at Microsoft.ServiceBus.Common.AsyncResult.TryComplete(Boolean, System.Exception)
   at Microsoft.ServiceBus.Common.AsyncResult.Complete(Boolean, System.Exception)
   at Microsoft.ServiceBus.Messaging.MessageReceiver+RetryReceiveAsyncResult+<GetAsyncSteps>d__15.MoveNext()
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].EnumerateSteps(CurrentThreadType<System.__Canon>)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].StepCallback(System.IAsyncResult)
   at Microsoft.ServiceBus.Common.AsyncResult.AsyncCompletionWrapperCallback(System.IAsyncResult)
   at Microsoft.ServiceBus.Common.AsyncResult.TryComplete(Boolean, System.Exception)
   at Microsoft.ServiceBus.Common.AsyncResult.Complete(Boolean, System.Exception)
   at Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessageReceiver+ReceiveAsyncResult+<GetAsyncSteps>d__12.MoveNext()
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].EnumerateSteps(CurrentThreadType<System.__Canon>)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].StepCallback(System.IAsyncResult)
   at Microsoft.ServiceBus.Common.AsyncResult.AsyncCompletionWrapperCallback(System.IAsyncResult)
   at Microsoft.ServiceBus.Common.AsyncResult.TryComplete(Boolean, System.Exception)
   at Microsoft.ServiceBus.Common.AsyncResult.Complete(Boolean, System.Exception)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement+ReconnectChannelFactory`1+RequestSessionChannel+RequestAsyncResult+<GetAsyncSteps>d__9[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].EnumerateSteps(CurrentThreadType<System.__Canon>)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].StepCallback(System.IAsyncResult)
   at Microsoft.ServiceBus.Common.AsyncResult.AsyncCompletionWrapperCallback(System.IAsyncResult)
   at Microsoft.ServiceBus.Common.AsyncResult.TryComplete(Boolean, System.Exception)
   at Microsoft.ServiceBus.Common.AsyncResult.Complete(Boolean, System.Exception)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].HandleException(System.Exception)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].StepCallback(System.IAsyncResult)
   at Microsoft.ServiceBus.Common.AsyncResult.AsyncCompletionWrapperCallback(System.IAsyncResult)
   at Microsoft.ServiceBus.Common.AsyncResult.TryComplete(Boolean, System.Exception)
   at Microsoft.ServiceBus.Common.AsyncResult.Complete(Boolean, System.Exception)
   at Microsoft.ServiceBus.Messaging.Channels.ReconnectBindingElement+ReconnectChannelFactory`1+RequestSessionChannel+RequestAsyncResult+<GetAsyncSteps>d__9[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].EnumerateSteps(CurrentThreadType<System.__Canon>)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].StepCallback(System.IAsyncResult)
   at Microsoft.ServiceBus.Common.AsyncResult.AsyncCompletionWrapperCallback(System.IAsyncResult)
   at Microsoft.ServiceBus.Common.AsyncResult.TryComplete(Boolean, System.Exception)
   at Microsoft.ServiceBus.Common.AsyncResult.Complete(Boolean, System.Exception)
   at Microsoft.ServiceBus.Messaging.Sbmp.DuplexRequestBindingElement+DuplexRequestSessionChannel+DuplexCorrelationAsyncResult.TryComplete(Boolean, System.Exception)
   at Microsoft.ServiceBus.Common.IOThreadScheduler+ScheduledOverlapped.IOCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
   at Microsoft.ServiceBus.Common.Fx+IOCompletionThunk.UnhandledExceptionFrame(UInt32, UInt32, System.Threading.NativeOverlapped*)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
</details>

**Comment by Scooletz** [comment]
I think we found the reason of this with @tmasternak . More info in https://github.com/Particular/NServiceBus.AzureServiceBus/issues/433

**Comment by Scooletz** [comment]
I reviewed again the exception details provided by @SeanFeldman https://github.com/Particular/NServiceBus.AzureServiceBus/pull/432#issuecomment-263437628 and still see a big potential in #433 . If the endpoint is stopped and tests finishes shutting down all the acceptance test infrastructure and the logging happens, it looks that it could be the same case.

**Comment by danielmarbach** [comment]
Closing in favor of https://github.com/Particular/NServiceBus.AzureServiceBus/pull/434

**Pull request closed without merging**
