### PR TITLE
Remove default sanitization

### PR DESCRIPTION
**Pull request by SeanFeldman**
Address issue #205 
Connect to https://github.com/Particular/PlatformDevelopment/issues/718

TLDR: ASB transport should by default throw an exception for entity names that are invalid rather than trying to sanitize that. Users can specify another strategy based on their needs. Default strategy will be `ThrowOnFailingSanitization`. For backward compatibility ~~`AdjustmentSanitizationV6`~~ `EndpointOrientedTopologySanitization` will be provided. Anything else will be provided as documentation.

### CODE REVIEW

**Comment by SeanFeldman** [comment]
@Particular/azure-service-bus-maintainers  please review

**Comment by yvesgoeleven** [comment]
looks good, will lead to doco changes though, can you handle those as well?

**Comment by SeanFeldman** [comment]
@yvesgoeleven correct, doco and sample for SHA1

**Comment by SeanFeldman** [comment]
@yvesgoeleven non of the changes showed up in your PR because they were reverted.

@SimonCropp what was the reason to revert this PR?

**Pull request merged**
