### PR TITLE
[WIP] Use publisher meta data to setup endpoint oriented topology

### PR DESCRIPTION
**Pull request by andreasohlund**
Updated to https://github.com/Particular/NServiceBus/pull/4246 locally and the pubsub tests run fine.

WIP since Core 6.1 needs to be available on myget in order to update.

Relevant code change: (should have made it a separate commit)

https://github.com/Particular/NServiceBus.AzureServiceBus/compare/use-publisher-metadata?expand=1#diff-ba2d9535a94c34a9c45553208d6c4856R36

### CODE REVIEW

**Comment by SeanFeldman** [comment]
👍 @andreasohlund

**Comment by yvesgoeleven** [comment]
@andreasohlund when do you expect 6.1?

**Comment by andreasohlund** [comment]
Dec 1 - https://github.com/Particular/NServiceBus/milestone/147

**Comment by andreasohlund** [comment]
Replaced by https://github.com/Particular/NServiceBus.AzureServiceBus/pull/449#issuecomment-265955056

**Pull request closed without merging**
