### PR TITLE
No longer register BatchedOperationsToBrokeredMessagesConverter and BrokeredMessagesToIncomingMessagesConverter on the container

### PR DESCRIPTION
**Pull request by danielmarbach**

### CODE REVIEW

**Comment by danielmarbach** [comment]
Rebased

**Comment by danielmarbach** [comment]
@SeanFeldman addressed your point and rebased.

**Comment by danielmarbach** [comment]
@yvesgoeleven please review and merge if happy

**Comment by yvesgoeleven** [comment]
I removed the keyword 'Default' from the classnames as they are not swappable anymore

**Pull request merged**
