### PR TITLE
Dependencies update (nunit 3 & GitVersionTask)

### PR DESCRIPTION
**Pull request by SeanFeldman**

### CODE REVIEW

**Comment by SeanFeldman** [comment]
@SimonCropp could you please have a look if I didn't miss anything? If all good, please merge.

**Comment by SimonCropp** [comment]
seems it broke the build :(

**Comment by SeanFeldman** [comment]
One of the tests is not supposed to be executed. Will fix tomorrow.

**Comment by SeanFeldman** [comment]
The failing test `When_saga_id_changed.Should_throw` seems to highlight an issue.
The exception that is expected is the one thrown by the core. Instead, we receive message lock exception which is happening after message is re-appearing 10 times on the queue after transport is actively aborts it.

It appears we know that receive operation is cancelled rather than exception being thrown (in `MessageReceiveNotifier`). @yvesgoeleven could you please have a look at it on Monday? Thank you.

**Comment by SeanFeldman** [comment]
`When_saga_id_changed.Should_throw` will be failing until the race condition is fixed in [ATT PR 3768](https://github.com/Particular/NServiceBus/pull/3768).

**Pull request merged**
