### PR TITLE
Update ASB client v5

### PR DESCRIPTION
**Pull request by SeanFeldman**
* Updated ASB client to v5
* Bumped .NET Framework to 4.6 (required by ASB client v5)

### CODE REVIEW

**Comment by SeanFeldman** [comment]
@danielmarbach you're commenting in your 😴 ?
Agreed, we're going to stick to 4.6. Question is - do we release this as a new major of the transport or not. Technically, it's a breaking change (.NET Framework update). cc @Particular/azure-maintainers

**Comment by yvesgoeleven** [comment]
If there are breaking changes, then it needs to be a major. If not, and it's just a nuget package update and nothing else, then we can release as a minor. As I see no code changes to make it work in this PR, I suggest it should be a minor

**Comment by SeanFeldman** [comment]
@yvesgoeleven it requires a framework bump. How is that a minor release? 🙂

**Comment by yvesgoeleven** [comment]
@SeanFeldman from our perspective nothing changed right? But some sys admin might need to install the new framework on the host machine for it to work?

**Comment by SeanFeldman** [comment]
Correct. And that might not be an option for them.

**Pull request merged**
