### PR TITLE
MaxDeliveryCount default value

### PR DESCRIPTION
**Pull request by SeanFeldman**
Addresses issue #137 

Connects to #92

### CODE REVIEW

**Comment by SeanFeldman** [comment]
@yvesgoeleven you've commented out the original code that used FLR/SLR. What was the reason?

**Comment by yvesgoeleven** [comment]
@SeanFeldman initialy I thought/reasoned that max delivery setting should be tied to FLR even when it's off. (aka 1 when no FLR). But in hindsight I think it's not true as FLR would move it to ErrorQ or SLR anyway.

**Comment by SeanFeldman** [comment]
@yvesgoeleven the outcome of the conversation taking place [here](https://github.com/Particular/NServiceBus/issues/3354) will influence this issue. For now I was thinking that `MaxDeliveryCount` should not be set to the default of ASB native service, but to the calculation to resolve number of total retries (influenced by FLR  and SLR) based on the [calculation in our doco](http://docs.particular.net/nservicebus/errors/automatic-retries#total-number-of-possible-attempts). 

I'm not sure if going with the formula `Total Attempts = (FLR:MaxRetries) * (SLR:NumberOfRetries + 1)` is the right option either, since not every delivery of a message will necessarily result in a processing attempt. Any ideas?

**Comment by yvesgoeleven** [comment]
@SeanFeldman should multiply by number of instances as well (and that is elastic), so you can't compute this up front

**Comment by yvesgoeleven** [comment]
leave it as is, we can't fix this unless we get control of the FLR & SLR mechanics

**Pull request merged**
