### PR TITLE
[WIP] hotfix 7.0.3

### PR DESCRIPTION
**Pull request by SeanFeldman**
#@internal issues will be used for release notes generation, not the PR

Hotfix for the following issues

- #411 (Topic existence is not verified with an associated namespace) ✔️ 
- #406 (FailOverNamespacePartitioning won't fail over): PRs: #415✔️, ~~#417✔️~~
- ~~#413 (RepeatedFailuresOverTimeCircuitBreaker is armed after a single error)❓~~

PR was started with fix to #411.

### CODE REVIEW

**Comment by SeanFeldman** [comment]
Targeting `master` branch.
@Particular/azure-service-bus-maintainers please review the proposed hotfix and discuss the changes.

**Comment by yvesgoeleven** [comment]
👍

**Comment by SeanFeldman** [comment]
During maintainers review today we've identified the following

1. #417 has to be reverted
1. Change performed in #415 did not address a problem with Dispatcher, that had to distinguish between active and passive namespaces. I.e. for first attempt sends, only active namespaces should used, not a mix of active and passive as it is right now. A separate PR will be issued to address that.

**Comment by SeanFeldman** [comment]
@Particular/azure-service-bus-maintainers all PR into hotfix were merged. This hotfix needs another complete review.

**Pull request merged**
